#docker-compose up --build

version: '3'

services:  

  db:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysqldata:/src/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet
    ports:
      - "3306:3306"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: brendonmascarenhas/nginx:nginxaasproxy
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
      
  nodejs:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: brendonmascarenhas/nodejs:nginxaasproxy
    container_name: nodejs
    networks:
      - nodenet
    entrypoint: ["/usr/src/app/docker-entrypoint.sh"]
    tty: true
    volumes:
    - ./node:/usr/src/app
    - /usr/src/app/node_modules 
   # command: node index.js

networks:
  nodenet:
    driver: bridge